### PR TITLE
Database management related changes

### PR DESCRIPTION
**Pull request by poontology**
In past node projects migration tools I've used have been part of ORM frameworks which can be quite complex and opinionated so I didn't think those were suitable. After short review of tools I picked dbmate over db-migrate mainly because it uses pure sql and it's active state info (schema version) stays with the db instead of being kept in a file.

So, in practice users who just use the provided dump and don't upgrade their code don't even need to care about this but anyone who has old db and new app code can do `npm run db-up` (dbmate up -v) which checks if schema_migrations table exists and is up-to-date with the migration files, if not it imports any new sql files and adds the version numbers to the table (for existing old db the initial schema basically does nothing since it's "create table if not exists"). Then there's `npx dbmate down` command that can be used to go back to previous schema version if desired for some reason (each migration file should know how to undo itself), and that's about it.

While testing realized something I'd forgotten about MyISAM (while not using mysql in past 15 years) is that it doesn't support transactions, it's a nice to have feature in case there is an error or user cancels the process so it could rollback any unfinished changes and make sure the db remains in consistent state, without rollback some of the sql operations may need to be run manually to make everything work again. OTOH, sql creates and alters are usually quick so user cancelling them probably isn't practical concern and data changes that could take some minutes often don't matter if they're cancelled, and schema/data changes should be in separate migration file anyway, so in other words: I don't think changing db engine to support transactions is warranted just for this use.

That being said, I did check out Aria engine a little bit and just doing `ALTER TABLE.. ENGINE=Aria;` to gid_tid, tag and gallery tables nearly halved the time for queries involving tags, too bad though it seems to be MariaDB exclusive engine not supported by Oracle's mysql. They also say that "Aria supports crash recovery, which makes it more resilient (than MyISAM) in the event of a system failure" not sure about the details of that one but anyway, that could be something to consider, is it worth it going mariadb exclusive?

Also couple other db things, every time conn.destroy() is called mariadb logs "[Warning] Aborted connection 59 to db: 'panda' user: 'root' host: '192.168.64.3' (Got an error reading communication packets)" because the connection was forcibly closed without letting it finish, not sure is there any real risk of data loss if query modified data but I think .end() is the more appropriate call regardless.
In the sukebei dump few unique indexes are little odd, gid_tid (gid_2) is a duplicate, some unique keys include the primary key which afaik makes the key not do anything to protect uniqueness because pkey is always unique by itself, so gallery (`posted`,`gid`) and `gid_posted_category_misc` could probably be replaced with something else. The initial schema sql were missing keys so I added a few.

Unrelated to db, maybe webpack build could also be made to happen at `npm start` so we didn't have to keep updating the build in git for every css change?

### CODE REVIEW

**Comment by poontology** [comment]
btw the app/action/ diffs look big but besides the thumb subselect I just wrapped the query inside try-finally to catch errors and close the connection cleanly without touching the code otherwise. in github diff-view's gear-menu changing from unified to split view might make it a little easier to read. of course I also tested that the api endpoints still work the same as they used to.

**Comment by poontology** [comment]
Also forgot to say, if you hashed files to previous table no need to redo they can be copied over after migration by running `insert into thumbnail (thumb,ph0,ph1,ph2,ph3,bitcount) select thumb,ph0,ph1,ph2,ph3,bitcount from gallery_thumb_hash h on duplicate key update ph0=h.ph0, ph1=h.ph1, ph2=h.ph2, ph3=h.ph3, bitcount=h.bitcount;` that updates thumbnails used by gallery and inserts the 150k rows that don't have gallery, although they don't get returned in search (actually, now thinking about it maybe it'd make sense for imagesearch to return those in search results too even if it's just the filename, will see about it later).

**Comment by UBTL** [comment]
Greetings, I actually have been quite busy with a lot of other projects and commission I work with so I haven't done anything new outside of just dump the new batch of thumbs and try to update the database to with both new data as well as add some other tables born from the idea or rather me having issues with how horseshit the Lanraragi project can be but there is no similar alternative out there focused fully on manga/doujin and metadata from panda or similar sites, would be nice if this project could also associated already downloaded dumps of zip/cbz files or folders so you could either read stuff directly off it just like LRR does minus deal with the damn thing, anyway here is the new Frankenstein database I was fucking with so if you wish to thinker with it or iunno here you go https://drive.google.com/drive/folders/1gkOQD2jMDmubbzmHdZk32OKkNV_rdzXU?usp=sharing , the thumbnails arent yet properly sorted into its folders so I will upload in that folder another time

**Comment by UBTL** [comment]
> That being said, I did check out Aria engine a little bit and just doing `ALTER TABLE.. ENGINE=Aria;` to gid_tid, tag and gallery tables nearly halved the time for queries involving tags, too bad though it seems to be MariaDB exclusive engine not supported by Oracle's mysql. They also say that "Aria supports crash recovery, which makes it more resilient (than MyISAM) in the event of a system failure" not sure about the details of that one but anyway, that could be something to consider, is it worth it going mariadb exclusive?

If it was just a marginally 5-9% improvement I would have just say to leave it up to the end user but a full reduction of about 50% for changing engines is too much to guaranteeing staying on MyISAM then, nevermind that I personally use MariaDB for projects that require MYSQL stuff anyway so if we can bring up such performance boosts then I accept to focus using only MariaDB from now on then if that is case, I accept going that route

**Comment by poontology** [comment]
Hi thanks for the gdrive, I'll have a look.

Re: query speed, one idea I was toying with was that when tags are involved in search it could query all the gids associated to those tags, keep them in memory and when user clicks the next page it'd use the gids in memory to fetch the galleries for, should be pretty fast. protyped something with ioredis which worked ok but then realized you could also just "create temporary table" with engine=memory and join with that one without adding any new dependencies (also instead of the cache having TTL the scripts that add new galleries could just drop the temporary table to get rid of cached tags). before committing to swapping to Aria engine we could see how that looks like.

Re: cbz, I wasn't actually familiar with Lanraragi only really played around with komga and kavita (although still mostly just using basic reader apps, like evince on linux), I see LRR also has OPDS for native reader apps. for me reading and searching for new content are two different usecases so I'm actually partial to the idea of having dedicated metadata system like pandabrowser separate from more general comics management platform. while those platforms have their own metadata db for the imported albums since they can get that metadata from a ComicInfo.xml included in the cbz I was thinking of a workflow/script where pandabrowser could identify the gid for given cbz, export a ComicInfo.xml file that's added in the cbz which is then imported to one of these other platforms. pandabrowser could then concentrate on features relating to discovery of new material (maybe add boomark lists for stuff to be downloaded etc?)

**Comment by poontology** [comment]
@UBTL played around with queries a bit (btw mistakenly said "temp table" in previous comment, those are tied to connections and disappear on every request so just regular in-memory table which would get replaced on every new search so only really useful to optimize queries for single-user system).. surprisingly caching the tid_gid select didn't help query time much at all then finally realized it wasn't the tag query that was slow, it was using "distinct" together with a large subselect. removed that and 8sec search dropped to ~1sec, about same time as the result total calculation query (the fact they were taking different times should've been a hint :smile:)
..edit: I should clarify, that was when searching for l:translated$ that gives 447717 results, more limited searches usually return in ~1sec anyway and removing distinct didn't really help them. do you happen to know if there was some reason distinct was used? as far as I can see the subselects shouldn't produce duplicate gids. also what kind of speeds are you seeing? there's some other optimizations that could still be applied for smaller tagsearches, eg. partitioning gid_tid appeared to shave off ~30%.

**Pull request merged**
