### PR TITLE
Add image similarity search feature

### PR DESCRIPTION
**Pull request by poontology**
Hi, here's a feature to add cover image file search similar to what e-hentai has. Earlier I used local python scripts to scan and rename my poorly organized cbz files with e-hentai gids, but thought it makes sense to have this as part of the UI.

It requires a new db table and adding an index to gallery

    CREATE TABLE `gallery_thumb_hash` (
      `thumb` varchar(150) NOT NULL, `ph0` smallint(5) unsigned NOT NULL, `ph1` smallint(5) unsigned NOT NULL, `ph2` smallint(5) unsigned NOT NULL, `ph3` smallint(5) unsigned NOT NULL, `bitcount` tinyint(4) NOT NULL, `added` timestamp NOT NULL DEFAULT current_timestamp(),
      PRIMARY KEY (`thumb`), KEY `bitcount_idx` (`bitcount`) USING BTREE
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    CREATE index gallery_thumb on gallery(thumb);

(Comparing image hash to all ~1.8M thumbnails in db takes 0.2sec with the index, without it takes >10sec as it scans the gallery table.)

The added dependencies are small and pretty standard (ie. millions of weekly downloads, multer is express middleware to handle file uploads, sharp is image manipulation lib that sharp-phash uses to calculate similarity hash for images, fast-glob scans directory to find the thumbnails, I would've used node builtins otherwise but recursive option for fs.readdir requires node20, tqdm is little less common but only ~100 LOC, easy to check at a glance, it renders a cmdline progressbar modeled after famous python lib of same name).

Interestingly my previous single-threaded python script hashed all the 1.8M jpgs and inserted to db in ~45min while the initial nodejs script looked like it'd take close to 6h, so I added multithreading to it and at 8 threads it took ~1h to get done (suspecting the perf difference is because of native numpy code in python but since processing everything only needs to be done once it doesn't make much sense to try optimizing the node script further).

There were some findings relating to the thumbnail files from the 42G zip file of 2024-02-15 sukebei release during this. 16 jpgs are partly broken, 70 jpg references in gallery are missing from the zip, 152860 jpgs are not used by any gallery, 505 thumbs in gallery-table are URLs pointing to exhentai and one broken non-jpg thumb URL, I can send details if you want to do updated zip release some day.

Some covers are of course used by many galleries (largest being 581 entries for "Furry Fight Chronicles" though most duplicates are just dozen or so entries) but that also means the hash table needs to use the filename as unique identifier and to join with gallery table, and I noticed that the thumb path includes `pandathumbs/12/34/1234567..jpg` although `1234567..jpg` would be enough, so I shortened it with `update gallery set thumb=REGEXP_REPLACE(thumb,'.*/','') where thumb like 'pandathumbs/%.jpg';` and changed Gallery.js so that it resolves the full path for the img itself (it also saves about 18*2e6*2=72MB in db size I think).
So to test this you'd also need to run that update sql for the file search to find the gallery entries.

Testing is pretty simple, after `npm i` do `npm run thumbs-phash all` or I could also upload csv dump of my hash-table somewhere (194M zipped) for importing?

### CODE REVIEW

**Comment by poontology** [comment]
Example of how to use the API from cmdline to find gid for a .cbz "cover" (first file when alphabetically sorted):
```
$ function unzipfirstfile { 7z x -so "$1" "$(zipinfo -1 "$1" | grep -v '/$' | sort -n | head -n1)"; }
# (using 7z because annoyingly unzip does wildcard matching and filenames with wacky characters cause "caution: filename not matched:")

$ unzipfirstfile pon8.part2.cbz | curl -sF file=@- 'http://0:6969/api/searchImage?out=gid' | jq .
{
  "code": 200,
  "data": [
    {
      "bc": 4,
      "gid": 922730
    }
  ],
  "message": "success",
  "total": 1
}
```
(bc=bitcount=hamming distance i.e. similarity score, <10=fairly similar, 0=exact match)

or also with a title..                                  
```
$ unzipfirstfile pon8.part2.cbz | curl -sF file=@- 'http://0:6969/api/searchImage' | jq -r '.data[0] | [.gid, .title] | @tsv'
922730  [Ponpharse] Ponpharse Vol. 8 - &quot;Yuuwaku -Futari dake no Himitsu-&quot; Hen PART2 | Ponpharse Vol. 8 - Seduction - A Secret Between the Two of Us - Part 2 [English] [TigorisTranslates]
```

**Comment by poontology** [comment]
Also, to support future db changes I'd suggest moving to use the semi-standard approach of having a "migrations" directory with timestamped sql files that are applied in sequence to update the system as new features get added (this requires a table where to put the name of the latest migration applied so it knows to apply only the newest changes). Basic table schema (eg. 20240101-0_init_schema.sql) could be included in git so that the app can operate without any data if someone wants to, the big SQL file (20240101-1_panda_data.sql.gz) only containing data can be downloaded separately, then this thumbnail schema change (20240918-0_gallery_thumb_hash_schema.sql) could again be in git and the data for it (20240918-1_gallery_thumb_hash_data.sql.gz) can be an optional download for whoever wants it. If ok I'll make a separate PR about that later.

**Comment by UBTL** [comment]
> There were some findings relating to the thumbnail files from the 42G zip file of 2024-02-15 sukebei release during this. 16 jpgs are partly broken, 70 jpg references in gallery are missing from the zip, 152860 jpgs are not used by any gallery, 505 thumbs in gallery-table are URLs pointing to exhentai and one broken non-jpg thumb URL, I can send details if you want to do updated zip release some day.

Are the 152860 JPGs pics of expunged galleries? since that seems about the number of galleries that has been thanos-out by now,  after all I dumped all the galleries thumbs links from the database dumps that has been released so they had to be *from some galleries* also if the size for them still "negligible" (just s few GBs at most) they should stay just in case imho, better be safe on that regard.
I do want a list for the missing 70 JPGs then please and 505 thumbs URLs that werent yet changed on the database since I was currently working on a updated database/new thumbs dump (is taking a while since It has been like over a year since I messed with this project and I completely didnt document how I supposedly converted/fixed the SQL database dump into the MYSQL so Im trying to figure it out again.

Noted regarding the database naming convention

**Comment by poontology** [comment]
Forgot how I arrived at 152860 exactly but rechecking gives 1749295-1596508=152787 (`find pandathumbs/ -type f | wc -l`=1749295, `select count(distinct thumb) from gallery where thumb not like '%/%';`=1596508). At ~25k each they take around 3.6GB, I'm fine with having them but it'd be nice to try figuring out what happened to the galleries where they're from, unsure how that could be done.

The partly broken jpgs are
```
88/2f/882fc39c09d8a2d83aaee55469fe2943b7f4a4ad-421559-708-1000-jpg_250.jpg
88/8d/888deebe8dd06c216e62e6d516e458d0916f2820-3959594-2090-3000-jpg_250.jpg
46/7f/467f9d60472588d7e59b8041166c46988c20b8ea-317481-1212-1600-jpg_250.jpg
ac/c4/acc4b8255e59947a4361b9a12f3dd01f3563ec2f-3025184-4183-6073-jpg_250.jpg
e1/e5/e1e5a20cefbdbadbb82aea86b9abdb3ecb96caf3-2312173-1480-2000-jpg_250.jpg
42/45/42454786d5f4db939f3780d5b9a48883b754a3c8-768700-1099-1600-jpg_250.jpg
6b/2e/6b2e448a3909a59484f5914ca0f728895980a074-400339-960-1440-jpg_250.jpg
1e/30/1e304d4327606259318c1831c53d20f6cba72b52-108259-585-832-jpg_250.jpg
c3/8a/c38a10463ffd5ec2b4d294bf0141678ea1d66b10-350002-810-1200-jpg_250.jpg
95/91/9591ef40bba2c58e3ca76bf906a779d56fc124e6-535776-1097-1600-jpg_250.jpg
1c/1c/1c1c20cb7143b8b9f08593f19403c86ba6598101-81210-387-516-jpg_250.jpg
e9/d8/e9d8c25703cb1b8b3c965c2b73eca7ed1a34b2b1-1158791-2480-3508-jpg_250.jpg
b1/6c/b16ca1be5a711c8696dc04857868dfdd28097a9e-1632555-1359-1920-png_250.jpg
9b/dc/9bdc26a0a19631f352fb07f8013e2ee9e251230e-306378-849-1167-jpg_250.jpg
fe/33/fe333cffc6081f50df7d067386dff30ae2da9dae-380024-974-1400-jpg_250.jpg
be/6a/be6ab89c1f5400d396a84230493513ef1309997a-227413-851-1200-jpg_250.jpg
da/1f/da1f802e0ba290add2f5913e0de76dd560c807e8-913364-1412-2000-jpg_250.jpg

```
The referenced but missing jpgs are
```
00162ab6fa1db885b331384c05d3d0fe1248ff95-1150392-320-240-gif_250.jpg
014c341b88d64bbae0e30d1b32f05a2067f6a861-204266-800-600-jpg_250.jpg
01fe8c06a186159cc3dd5fe79614a5eb95014237-205477-1920-1080-jpg_250.jpg
0e42c7c9577265d665a2674bc9d51ba868cee385-2908346-176-120-gif_250.jpg
0e54cbb047d65af52f26fd4736f704dcda8065f1-398215-320-240-gif_250.jpg
161efa3b298462807cb3a89bbd1fa558cfec6a8d-833424-1119-1600-jpg_250.jpg
1a0fbb17f86abf25eeb6ed2ec608b6f67f0f25bb-1321958-1622-2741-jpg_250.jpg
2ac490df03e18ab3a89c730d342b394dbbb34069-56255-460-575-jpg_250.jpg
2babac4d89a9abdad327af5c7ce9ba9575a552cb-14542-568-470-jpg_250.jpg
2bf4153ff3b5a3589e39305be70d0790fb21896d-825676-4961-3508-jpg_250.jpg
2db19fae6772c153e424147bce7d194614172140-3980914-2480-3524-jpg_250.jpg
2f77f068add31a81dcf355285d34b86b2f449669-882438-452-302-gif_250.jpg
38f54b28e26f45be2cdfb1d18cdf567e46673061-5927176-512-288-gif_250.jpg
3a7163a9c026a0ac9403b732f3e397ee17b2e6ea-522742-900-1260-jpg_250.jpg
3c29bf5a27e631dd0d1fd8458d5962fe3b3e65ea-1236917-500-375-gif_250.jpg
40eac5ba041a6559a6796abf5ee32d4e76beccf8-2312298-2270-3857-jpg_250.jpg
46209b2ed09caac84d88a61871e1c522815d9e35-453625-1145-1600-jpg_250.jpg
486ecae037f83081f6ca38aa7b962e7af0187c8f-385525-1131-1475-jpg_250.jpg
514eb675f4d0e541f0d3fba834823921f700761d-97205-1200-910-jpg_250.jpg
564f76d6b3c50c4203f13729c8d7fc18625add3a-1155820-1620-2878-jpg_250.jpg
59c5d51b672d7a1f6b82f426e6b80190e0e7bcd0-2193339-320-240-gif_250.jpg
5ed841952345208d9641eb049ab9ca0b0a1ef140-5654379-301-170-gif_250.jpg
61c43cf0d94dea5bbe49bcc536258b2c7643bc80-1344841-1622-2861-jpg_250.jpg
6251f2ec3f15eab73dcefd69d3848fdb7d02178b-1762794-2384-3264-jpg_250.jpg
66225c5d530ad440b9f1145474e66df4a176dad9-1859096-2270-3857-jpg_250.jpg
66fcdb98344f5347d95f2d643e2bc9b1e43be86f-157821-1920-1080-jpg_250.jpg
7110144faeea438d6d89753995972697d4193643-76890-985-767-jpg_250.jpg
75930b5ab5d85fc6418f0404f2acc00f0edc8993-454367-320-240-gif_250.jpg
76c1a8d3929bf6dbcedc6e997f799dc1743f58e5-75852-640-480-png_250.jpg
79b606b73872ffe4ce8c883145e59ab3cb92f539-81296-800-600-jpg_250.jpg
7dbdb60e89cd7eb9aa88d1196edbc3290e732c6b-108659-653-373-jpg_250.jpg
82b1db1dbea7e19168774ecb82b19f6587f9337b-719644-170-128-gif_250.jpg
84e9accd56b9e3ceb34371c514e2b52b0d1edfb1-830058-2073-3056-jpg_250.jpg
87be6a8dcffa9e25c548471f7574d8236c384908-877546-2160-2880-jpg_250.jpg
8f4a5995ba9e14c0b1e512fb51f7caf32dd7ed0d-80415-800-600-jpg_250.jpg
8f6cefae9f72388df68fbf43ddbee232b5e2452d-257948-1152-2028-jpg_250.jpg
91370470401b7925ce0fcf8794d01a6f9c70fa47-2429743-2270-4032-jpg_250.jpg
949bf27f2560a9cc961a19d67179a3ad220c9fbd-218383-1153-1782-jpg_250.jpg
9807b6039fe06bdecf0d23acd3d2e400a5ef734f-234842-1016-1747-jpg_250.jpg
9c3db8566880cef21a70ff9b4811f75945e7fd3a-1944695-2270-3857-jpg_250.jpg
a0b721417e3a6249accde52a680ccba8f01a7db2-206766-1080-1920-jpg_250.jpg
a31bd5349ae4601440ab043f6241b9c3e01d747c-47971-900-600-jpg_250.jpg
a7044eb3224eb22f23682a01dd28335ca553bc87-1677706-1500-2048-jpg_250.jpg
a864e6dcffb343949cfa8b66d06d28b846995588-2472169-2270-4032-jpg_250.jpg
a929efb4a64e04bde0be75547c80c893b5c14fbd-982032-1622-2587-jpg_250.jpg
ab4211d12faa78897d1139b300139d88f26e3f95-923653-640-480-png_250.jpg
b16ca1be5a711c8696dc04857868dfdd28097a9e-1632555-1359-1920-png_250.jpg
b38f2fc78ed3976c494cbe6d3b6f06e4298b61a1-526820-1840-2803-jpg_250.jpg
b5b0750e43d00f1ec9c6711619258a323dd3ba97-438977-1260-2048-jpg_250.jpg
b86371feaee8e5bb2634d3febd58a6ce2669f07b-9799600-5664-2481-jpg_250.jpg
b8d2f1b205c9eacd4a6ee4ee17cab93d9d84da13-1667734-2270-3689-jpg_250.jpg
b92af18cedb293dfc75e3ca88511842072114b70-1333275-800-1100-png_250.jpg
b9e23917d9048fe6718006dd7e98a374207e4e23-1400073-1000-1376-jpg_250.jpg
bbf24322a62bb5b3904e68cf6ec7c8ac51570136-199969-794-1024-jpg_250.jpg
bc093a0666ce6f627509139b71c9a826d71da8b4-1083339-1622-2746-jpg_250.jpg
becee9b2aa52aa7e89d43733910af660dcc9e525-2025708-2162-3840-jpg_250.jpg
c1fcf077f80e81be517b78e2293ef62881c00058-1209549-957-1375-jpg_250.jpg
d1467c56df92f7e1051cd899e1df85ae7a0e28ae-476446-1242-2208-jpg_250.jpg
dd8d114c282d1753a2edcb45967e8d91589b24a5-776690-960-1280-png_250.jpg
e0559c734fe797d25a656e0de62a82a3f6f5ff66-719652-1754-2481-jpg_250.jpg
e3815875e1b3c7a5282aa95b161a402dad7b0c4d-1710007-2260-1600-jpg_250.jpg
e5eb149b017650726104566a48ecca45c7e140c0-144199-800-1200-jpg_250.jpg
e72b6488f52acffe48113da22378cd4caa4a65df-284775-1152-1792-jpg_250.jpg
e73118a30ba061d28fdeaf8bb36f0a45c97a8475-910602-1600-1200-jpg_250.jpg
eaf87a25c0fb7a7ea3baef2c54c418c24f2b34a7-446503-1420-2000-jpg_250.jpg
ef08046cda77ec18dec440cd94d07ce6700b4303-33198-1024-768-jpg_250.jpg
f04d9c78ad9b5d8691f6a22f091439dd4f431348-1990204-2270-4032-jpg_250.jpg
f20aca06b64cd4993a1f46f894b4f89e7d04c11c-4017-502-632-jpg_250.jpg
f222e0609e03420aa53411f6361b03ab6c5019b6-141542-560-420-jpg_250.jpg
f36c96348a0ea598d3267e523affdc7a2599ac6e-1334260-512-288-gif_250.jpg
f40d82922f5c26417f0ccbf89aeb891570b5a3dd-1490301-2270-4032-jpg_250.jpg
f642eb4942cb267e9e416af0f3d8cf38cd257e90-951694-1622-2880-jpg_250.jpg
f7b09fa888dad4996cef6ce8145d8610eb2ce7c2-9609829-336-189-gif_250.jpg
fba690219bd8f6c94997c4568a269be41b1bba4c-2081812-1496-2112-jpg_250.jpg

```

**Comment by poontology** [comment]
@UBTL Thinking more about the db it's making sense to me now that the new table should've actually been a `thumbnail` table with a numeric id and to replace `thumb`  column in `gallery` there would be `thumbnail_id`. Besides it being a bit silly for the new hash table to duplicate all that text data from gallery table, gallery also has 373291 duplicate thumbnail filenames when it could just be a short id number instead. (afaik the fancy dbms terms for it is "decomposition" and "normalization", there's this whole academic thing about "normal forms" that I never had the patience to learn properly). Will do a PR to refactor it a bit by tomorrow.

**Pull request merged**
