### PR TITLE
stand-alone executable build

### PR DESCRIPTION
**Pull request by poontology**
this is pretty cool, it creates a stand-alone executable.
it contains the whole app including nodejs so user doesn't need to install anything, just download it into directory with pandathumbs and db-subdirs (with files from the gdrive 7z), run the executable and the system is ready to use.
(for packaged build the config.js defaults to using sqlite and having personal features enabled, we could maybe add cmdline options for user to set db details, paths etc)

the build gets triggered when a git tag with pattern v#.#.# is created, it runs the steps seen here:
  https://github.com/poontology/pandabrowser/actions/runs/11321198310
that run created this release:
  https://github.com/poontology/pandabrowser/releases/tag/v0.3.2-test3
(only tested the linux build but I guess win and macos should work too)

hooked it up so that it can theoretically run cli js scripts from inside the pkg but if the script wants to handle process.argv it doesn't work out-of-box, phash script doesn't need it so at least it works

    $ ./panda-browser run thumbs-phash
    checking status ...
    found 1971557 hashes in db (1955ms)
    found 1971557 thumb files (3414ms)
    found 0 files to process

easiest way to make the other scripts work would probably be to add alternate entrypoint function for pkg'd index.js

### CODE REVIEW

**Comment by poontology** [comment]
was testing in dir that included node_modules and noticed it loaded one binary from there instead of the pkg so those test2 executables might not actually run standalone, here's a [new test3 release build](https://github.com/poontology/pandabrowser/releases/tag/v0.3.2-test3)

**Comment by UBTL** [comment]
Also it is me or this feature isnt yet implemented? the Have/Read/Want

**Comment by UBTL** [comment]
Also I had the thoughts of doing a build binary version sure, but on windows the issue for starter is if you dont sign your binaries your average user will at best get the dreaded


And if not this


I got both btw

**Comment by UBTL** [comment]
So for windows people will need to dowload NodeJS themselves and run it through the command line most likely, that is of course for those that arent enthusiast enough to already have some sort of home server machine that is running a proper version of Linux flavor

**Comment by poontology** [comment]
oh right of course forgot about codesigning, haven't really used windows in years. apparently OV cert is ~$200/yr so I guess that's not happening any time soon.

hm the path I have for sharp module is node_modules/sharp/build/Release/sharp-win32-x64.node.win.v18.5.0 not sure if it goes in the pkg like that, could debug a bit but maybe this isn't worth pursuing if it can't be easily used in windows and most linux users likely wouldn't use stand-alone executable anyway.

the have/read/want works ok for me, how does it look for you? did you enable personal flag from config.js?
edit: ah yea you aren't probably using webpack-dev-server so `npm run build` needs to be run after changing config.js for it to get included in the react app.

**Comment by UBTL** [comment]
Yeah dont spend time on building such type of binaries since for windows end users will most likely not happen because of the lack of code signing and windows defender most likely purging the file seeing it as a virus and your average linux user will just install stuff the usual node way, also whatever that needs to be build/added to the project preadd it then so the only 2 commands of the end user has to use should be hopefully npm install and npm start

**Comment by poontology** [comment]
hadn't noticed the release and commit from few days ago, re: commit, dbmate doesn't recognize .txt extension, if the migrations are to be used they should remain .sql files.. but perhaps it's simpler to go without, made a new PR.

re: stand-alone build yea executable is likely off the table I do wonder if it'd still be useful to try to package everything into one file that's execute with user's own installation of nodejs that way side-stepping the signing issue, but I'll look into it another time.

btw, I mentioned adding `npm run build` to the start command in some previous comment, that would keep config.js included for UI and remove the need to make separate webpack build commits for UI stuff, but it does add 5sec to each `npm start`, how does that sound?

**Comment by UBTL** [comment]
I mean, if we ask the normal windows user to just run that command it may give them this message

657657547u

**Comment by poontology** [comment]
ah. you probably have "git bash" installed? (it's a command shell ported from linux that comes with windows git installation), try with that (just cd into directory and `npm run build` nothing fancy needed).

or alternatively just remove "env NODE_ENV=production" from package.json, it's just optimization option that packages the files bit more efficiently.

anyway if I add `build` to the `start` command I'll see that it works on windows command prompt same as before.

**Comment by poontology** [comment]
@UBTL oh you merged? I was actually going to close this PR since the changes are just related to creation of the executable build.. they shouldn't prevent the app from normally of course either so I guess it's ok.

although.. I think the lock file merge conflict went wrong way around, as it is now the package-lock.json has different versions than package.json could you run `npm install` and commit that package-lock.json?

**Comment by UBTL** [comment]
If someone somehow wants to make a build for who knows, internal sharing or something like some sort of archival or who knows and its pretty much optional, sure lets just add it in, is entirely up to the end user on that regard, btw is the ComicInfo thing working already, I tried to use with an example of http://localhost:6969/api/comicInfo/838471 and its giving me the message of
> {"code":400,"data":null,"message":"gid is invalid"}

tried with other gids

**Comment by poontology** [comment]
I didn't map gid as a path parameter so it's /api/comicInfo/?gid=838471
guess path parameter would make sense though as it's a single item that's being queried for .. if you want to change it should be enough to do `router.use('/:gid',` in router/api/comicInfo.js should probably update API.md then to match the change.

**Pull request merged**
